export let kanbanData: Object[]=[
  {
    'id': 18,
    "date": "23/02/2022",
    "location": "",
    'companyName': "xyz",
    "numOfEmployee": 0,
    "turnover": "",
    "source": "",
    "contactPerson": "Shilpi Goel",
    "designation": "",
    "phoneNumber": "9811604000",
    "message": "not required",
    "email": "shilpi.goel2210@gmail.com",
    "leadType": "",
    "productInterest": "",
    "Status": "FollowUp",
    "timestamp": "2022-09-26 2:43:18 PM",

  },
  {
    'id': 14,
    "date": "2022-09-22",
    "location": "",
    'companyName': "Cinntra SRC",
    "numOfEmployee": 0,
    "turnover": "",
    "source": "LinkedIn",
    "contactPerson": "saurabh",
    "designation": "",
    "phoneNumber": "0987654343",
    "message": "qualified",
    "email": "",
    "leadType": "",
    "productInterest": "",
    "Status": "Junk",
    "timestamp": "2022-09-22 2:38:33 PM",

  },
  {
    'id': 13,
    "date": "2022-09-22",
    "location": "",
    'companyName': "saurabh tech",
    "numOfEmployee": 0,
    "turnover": "",
    "source": "LinkedIn",
    "contactPerson": "saurabh",
    "designation": "",
    "phoneNumber": "0987654367",
    "message": "hold",
    "email": "",
    "leadType": "Hot",
    "productInterest": "",
    "Status": "Hold",
    "timestamp": "2022-09-22 2:38:09 PM",

  },
  {
    'id': 7,
    "date": "2022-09-16",
    "location": "Delhi",
    'companyName': "cinntra",
    "numOfEmployee": 0,
    "turnover": "",
    "source": "Reference",
    "contactPerson": "Arif",
    "designation": "",
    "phoneNumber": "7905433865",
    "message": "Testing",
    "email": "arif.ansari@cinntra.com",
    "leadType": "Hot",
    "productInterest": "yes",
    "Status": "FollowUp",
    "timestamp": "2022-09-16 2:28:08 PM",

  }
];
